### ISSUE TITLE
Related data problems

### ISSUE THREAD

**Issue by sxy1122** [PuAnysh/UFPMP-Det#1]
Hello, I have a few questions I'm not sure about. I'd like to ask. Is the data set for rough detection in coco format from the beginning? In addition, when performing fine detection, is the data set obtained after UFP processing?

# conver VisDrone to COCO
python UFPMP-Det-Tools/build_dataset/VisDrone2COCO.py
# conver UAVDT to COCO
python UFPMP-Det-Tools/build_dataset/UAVDT2COCO.py
# build UFP dataset(VisDrone)
CUDA_VISIBLE_DEVICES=2 python UFPMP-Det-Tools/build_dataset/UFP_VisDrone2COCO.py \
    ./configs/UFPMP-Det/coarse_det.py \
    ./work_dirs/coarse_det/epoch_12.pth \
    xxxxxx/dataset/COCO/images/UAVtrain \
    xxxxxx/dataset/COCO/annotations/instances_UAVtrain_v1.json \
    xxxxxx/dataset/COCO/images/instance_UFP_UAVtrain/ \
    xxxxxx/dataset/COCO/annotations/instance_UFP_UAVtrain.json \
    --txt_path path_to_VisDrone_annotation_dir

**Comment by sxy1122** [comment]
'please specify them in model', UserWarning)
load checkpoint from local path: ./work_dirs/coarse_det/epoch_12.pth
loading annotations into memory...
Done (t=1.33s)
creating index...
index created!
Traceback (most recent call last):
  File "UFPMP-Det-Tools/build_dataset/UFP_VisDrone2COCO.py", line 205, in <module>
    main()
  File "UFPMP-Det-Tools/build_dataset/UFP_VisDrone2COCO.py", line 160, in main
    img_name = coco.imgs[key]['file_name']
KeyError: 0

Hello, this problem appears in your article. Would you like to ask me what's wrong with my operation? I don't know how to solve it?

**Comment by PuAnysh** [comment]
Yes, In the first stage, we use a coarse detector to generate the foreground region on raw images. we use coco format dataset for training convenience. In the second stage, we use UFP processing to generate the Packed images for MP-Det training.

The error that occurred in your issue may be caused by wrong annotation files(*.json). I test this script on my computer. The correct result as follow:
![微信图片_20220331234019](https://user-images.githubusercontent.com/34938360/161095448-7f6954f3-889d-4919-8721-1708ef17523d.png)

**Comment by sxy1122** [comment]
Excuse me, what do these values mean and where did you get them?

![image](https://user-images.githubusercontent.com/77336413/161260064-3cc6e70f-ce2f-4770-8449-405fde4b79f5.png)

**Comment by sxy1122** [comment]
> Yes, In the first stage, we use a coarse detector to generate the foreground region on raw images. we use coco format dataset for training convenience. In the second stage, we use UFP processing to generate the Packed images for MP-Det training.
> 
> The error that occurred in your issue may be caused by wrong annotation files(*.json). I test this script on my computer. The correct result as follow: ![微信图片_20220331234019](https://user-images.githubusercontent.com/34938360/161095448-7f6954f3-889d-4919-8721-1708ef17523d.png)

What should I do? Replace json file of data？I want to know how to generate a new data set according to the existing data results and send it to the back for re detection? Is it the part of your code provided by the UFP_VisDrone2COCO.py?

**Comment by PuAnysh** [comment]
> Excuse me, what do these values mean and where did you get them?
> 
> ![image](https://user-images.githubusercontent.com/77336413/161260064-3cc6e70f-ce2f-4770-8449-405fde4b79f5.png)

Hi, this is a test code for the UFP algorithm. The input is a List of Bbox[x1, y1, x2, y2].

**Comment by PuAnysh** [comment]
> > Yes, In the first stage, we use a coarse detector to generate the foreground region on raw images. we use coco format dataset for training convenience. In the second stage, we use UFP processing to generate the Packed images for MP-Det training.
> > The error that occurred in your issue may be caused by wrong annotation files(*.json). I test this script on my computer. The correct result as follow: ![微信图片_20220331234019](https://user-images.githubusercontent.com/34938360/161095448-7f6954f3-889d-4919-8721-1708ef17523d.png)
> 
> What should I do? Replace json file of data？I want to know how to generate a new data set according to the existing data results and send it to the back for re detection? Is it the part of your code provided by the UFP_VisDrone2COCO.py?


Quickly start:
I have provided this JSON file on the coco format dataset. This JSON file is the original annotations of the VisDrone dataset.
DIY:
Please see: https://github.com/PuAnysh/UFPMP-Det/blob/main/UFPMP-Det-Tools/build_dataset/VisDrone2COCO.py
